In [1]:
import pandas as pd
import ast

# Load the CSV file
file_path = r"C:\Users\sandy\Downloads\Hyderabad_output_file.csv"  # Adjust this if necessary
df = pd.read_csv(file_path)

# Function to par'se the JSON-like strings into actual dictionaries
def parse_json_column(column):
    return column.apply(lambda x: ast.literal_eval(x))

# Parsing the columns
df['new_car_detail'] = parse_json_column(df['new_car_detail'])
df['new_car_overview'] = parse_json_column(df['new_car_overview'])
df['new_car_feature'] = parse_json_column(df['new_car_feature'])
df['new_car_specs'] = parse_json_column(df['new_car_specs'])

# Extracting details from 'new_car_detail'
df_details = pd.json_normalize(df['new_car_detail'])

# Extracting overview from 'new_car_overview'
df_overview = pd.json_normalize(df['new_car_overview'].apply(lambda x: x.get('top', {})))

# Extracting features from 'new_car_feature'
df_features = pd.json_normalize(df['new_car_feature'].apply(lambda x: x.get('top', {})))

# Extracting specifications from 'new_car_specs'
df_specs = pd.json_normalize(df['new_car_specs'].apply(lambda x: x.get('top', {})))

# Extracting additional data from 'new_car_overview', 'new_car_feature', and 'new_car_specs' if present
df_overview_data = pd.json_normalize(df['new_car_overview'].apply(lambda x: x.get('data', {})))
df_features_data = pd.json_normalize(df['new_car_feature'].apply(lambda x: x.get('data', {})))
df_specs_data = pd.json_normalize(df['new_car_specs'].apply(lambda x: x.get('data', {})))

# Combine all extracted data into a single dataframe
df_final = pd.concat([df_details, df_overview, df_features, df_specs, 
                      df_overview_data, df_features_data, df_specs_data,
                      df['car_links']], axis=1)

# Save the structured data to your specified path
output_file = 'C:/Users/sandy/Desktop/Project_realected_practice/Car_deako/Structed_Hyderabad_cars.csv'
df_final.to_csv(output_file, index=False)

print(f"Structured data saved to {output_file}")

Structured data saved to C:/Users/sandy/Desktop/Project_realected_practice/Car_deako/Structed_Hyderabad_cars.csv

In [2]:
import pandas as pd
First=pd.read_csv(r'C:/Users/sandy/Desktop/Project_realected_practice/Car_deako/Structed_Hyderabad_cars.csv')
First.head()

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,5.2,0.3,1.3,2.3,3.3,4.3,0.4,1.4,2.4,car_links
0,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,2022,...,"{'key': 'Seats', 'value': '5'}","{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '...","{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi...",https://www.cardekho.com/used-car-details/used...
1,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,2014,...,NaN,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...",NaN,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi...",https://www.cardekho.com/buy-used-car-details/...
2,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,2023,...,NaN,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '...","{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi...",https://www.cardekho.com/used-car-details/used...
3,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,2017,...,"{'key': 'Seats', 'value': '5'}","{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '...","{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi...",https://www.cardekho.com/buy-used-car-details/...
4,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,2022,...,NaN,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '...","{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi...",https://www.cardekho.com/used-car-details/used...

In [3]:
import pandas as pd
import ast

def process_cell(cell):
    if pd.isna(cell):
        return {}
    try:
        data = ast.literal_eval(cell)
        if isinstance(data, dict):
            return data
    except (ValueError, SyntaxError):
        return {}
    return {}

def transform_data(input_file, output_file):
    # Load the CSV file
    data = pd.read_csv(input_file)

    # Apply the function to relevant columns to convert JSON-like strings into dictionaries
    json_columns = data.columns[18:52]
    for col in json_columns:
        data[col] = data[col].apply(process_cell)

    # Initialize a list to hold the structured data rows
    structured_data_rows = []

    # Process each row to extract and organize the structured data
    for index, row in data.iterrows():
        new_row = {}
        specification_count = 1
        
        for col in json_columns:
            cell_data = row[col]
            
            # Type 1 and Type 4: Key-Value pairs
            if 'key' in cell_data:
                new_row[cell_data['key']] = cell_data['value']
            
            # Type 2: Only Value
            elif 'value' in cell_data and 'key' not in cell_data:
                new_row[f'specification{specification_count}'] = cell_data['value']
                specification_count += 1
            
            # Type 3: Heading with list of values
            elif 'heading' in cell_data and 'list' in cell_data:
                values_list = [item['value'] for item in cell_data['list']]
                new_row[cell_data['heading']] = values_list
        
        # Append the new row dictionary to the list of structured data rows
        structured_data_rows.append(new_row)

    # Convert the list of dictionaries to a DataFrame
    structured_data = pd.DataFrame(structured_data_rows)

    # Merge the structured data back with the original data (excluding JSON columns)
    final_data = pd.concat([data.drop(columns=json_columns), structured_data], axis=1)
    
    # Save the final structured data to a new CSV file
    final_data.to_csv(output_file, index=False)

# Usage
input_file = r'C:\Users\sandy\Desktop\Project_realected_practice\Car_deako\Structed_Hyderabad_cars.csv'
output_file = r'C:\Users\sandy\Desktop\Project_realected_practice\Car_deako\structured_data_Hyderabad.csv'
transform_data(input_file, output_file)

In [4]:
import pandas as pd
First_2=pd.read_csv(r'C:\Users\sandy\Desktop\Project_realected_practice\Car_deako\structured_data_Hyderabad.csv')
First_2.head()

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Torque,Wheel Size,Comfort & Convenience,Interior,Exterior,Safety,Entertainment & Communication,Engine and Transmission,Dimensions & Capacity,Miscellaneous
0,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,2022,...,175nm,R16,"['Power Steering', 'Power Windows Front', 'Pow...","['Air Conditioner', 'Heater', 'Adjustable Stee...","['Adjustable Head Lights', 'Fog Lights Front',...","['Anti Lock Braking System', 'Centeral Locking...","['Radio', 'Speakers Front', 'Speakers Rear', '...","['Others', '1.0L TSI Petrol', '999', '108.62bh...","['3971mm', '1682mm', '1469mm', '2470mm', '1457...","['6 Speed', 'FWD', '5', 'Electronic', '4.9', '..."
1,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,2014,...,74.5Nm,NaN,"['Power Steering', 'Power Windows Front', 'Rem...","['Air Conditioner', 'Heater', 'Digital Odomete...","['Adjustable Head Lights', 'Manually Adjustabl...","['Child Safety Locks', 'Driver Air Bag', 'Day ...",NaN,"['Red', 'Petrol Engine', '814', '55.2bhp@5500r...","['3495mm', '1550mm', '1500mm', '2380mm', '1386...","['5 Speed', 'FWD', '5', 'Power', '4.6 metres',..."
2,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,2023,...,113.8Nm,NaN,"['Power Steering', 'Power Windows Front', 'Pow...","['Air Conditioner', 'Heater', 'Adjustable Stee...","['Adjustable Head Lights', 'Power Adjustable E...","['Anti Lock Braking System', 'Brake Assist', '...","['Radio', 'Speakers Front', 'Speakers Rear', '...","['Others', '1.2 Kappa Petrol', '1197', '81.80b...","['3995mm', '1770mm', '1617mm', '2500mm', '1106']","['5-Speed', '5', 'Power', 'Disc', 'Drum', 'Tub..."
3,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,2017,...,115Nm,16,"['Power Steering', 'Power Windows Front', 'Pow...","['Air Conditioner', 'Heater', 'Adjustable Stee...","['Adjustable Head Lights', 'Fog Lights Front',...","['Anti Lock Braking System', 'Centeral Locking...","['Radio', 'Audio System Remote Control', 'Spea...","['Red', 'VVT Petrol Engine', '1197', '83.1bhp@...","['3995mm', '1745mm', '1510mm', '2520mm', '1505...","['5 Speed', 'FWD', '5', 'Power', '4.9 meters',..."
4,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,2022,...,320Nm,18,"['Power Steering', 'Power Windows Front', 'Low...","['Air Conditioner', 'Heater', 'Adjustable Stee...","['Adjustable Head Lights', 'Fog Lights Front',...","['Anti Lock Braking System', 'Brake Assist', '...","['Radio', 'Speakers Front', 'Speakers Rear', '...","['Others', 'mStallion 150 TGDi Engine', '1997'...","['3985mm', '1855mm', '1844mm', '2450mm', '1520...","['6 Speed', '4X4', '4', 'Power', 'Disc', 'Drum..."

In [3]:
import pandas as pd

# Load the structured CSV file
file_path = r'C:\Users\sandy\Desktop\Project_realected_practice\Car_deako\structured_data_Hyderabad.csv'
data = pd.read_csv(file_path)

# List of columns that contain lists of values
list_columns = [
    'Interior',
    'Safety',
    'Miscellaneous',
]

# Function to split list values into separate columns
def split_list_into_columns(row, col_name):
    values = row[col_name]
    if pd.isna(values):
        return {}
    
    values = values.strip('[]').split(',')
    values = [v.strip().strip("'") for v in values]
    
    split_columns = {f'{col_name}{i+1}': values[i] for i in range(len(values))}
    return split_columns

# Apply the function to each row and update the dataframe
for col in list_columns:
    new_columns = data.apply(lambda row: pd.Series(split_list_into_columns(row, col)), axis=1)
    data = pd.concat([data, new_columns], axis=1)
    data.drop(columns=[col], inplace=True)

# Save the updated dataframe to a new CSV file
output_file_path = r'C:\Users\sandy\Desktop\Project_realected_practice\Car_deako\Hyderabad.csv'
data.to_csv(output_file_path, index=False)

output_file_path

'C:\\Users\\sandy\\Desktop\\Project_realected_practice\\Car_deako\\Hyderabad.csv'

In [4]:
import pandas as pd
import ast

# Step 1: Load the data
df = pd.read_csv(r"C:\Users\sandy\Desktop\Project_realected_practice\Car_deako\Hyderabad.csv")
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Miscellaneous13,Miscellaneous14,Miscellaneous2,Miscellaneous3,Miscellaneous4,Miscellaneous5,Miscellaneous6,Miscellaneous7,Miscellaneous8,Miscellaneous9
0,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,2022,...,NaN,NaN,FWD,5,Electronic,4.9,Disc,Drum,Tubeless,Radial
1,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,2014,...,NaN,NaN,FWD,5,Power,4.6 metres,Disc,Drum,135 Kmph,19 Seconds
2,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,2023,...,NaN,NaN,5,Power,Disc,Drum,Tubeless,Radial,5,NaN
3,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,2017,...,5,339-litres,FWD,5,Power,4.9 meters,Disc,Drum,180 Kmph,12.36 seconds
4,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,2022,...,NaN,NaN,4X4,4,Power,Disc,Drum,Radial,Tubeless,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,2013,...,5,NaN,FWD,7,Power,5.6 metres,Disc & Caliper Type,Disc & Caliper Type,175 kmph,12.5 Seconds
1479,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,2014,...,4,540-litres,RWD,5,Power,5.75 metres,Disc,Disc,250 Kmph,6.4 Seconds
1480,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,2018,...,4,520-litres,RWD,5,Power,5.6,Ventilated Disc,Ventilated Disc,235kmph,7.5
1481,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,2019,...,NaN,NaN,FWD,5,Power,5.1m,Disc,Drum,154.19 kmph,13.25 Seconds
1482,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,2015,...,5,300-litres,RWD,7,Power,5.4 metres,Ventilated Disc,Drum,155 Kmph,13.3 Seconds